# Controller config for testing franka_policy_controller through franka_bringup.

/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_policy_controller:
        type: franka_policy_controller/FrankaPolicyController

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

/**:
  franka_policy_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      p_gains: [60.0, 60.0, 60.0, 60.0, 25.0, 15.0, 5.0]
      d_gains: [6.0, 6.0, 6.0, 6.0, 2.0, 2.0, 1.0]
      effort_limits: [5.0, 5.0, 5.0, 5.0, 3.0, 2.0, 1.0]
      reference_timeout_sec: 2.0
